language: cpp
compiler: gcc
branches:
  only:
    - master
    - develop
    - /^hotfix\/.*/
    - /^release\/.*/
before_script:
  - export DISPLAY=:99.0
  # initialize virtual framebuffer x-server for GUI testing
  - sh -e /etc/init.d/xvfb start
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty universe"
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty main"
  - sudo apt-get update -qq
  - sudo apt-get install gcc-5 g++-5 qtbase5-dev qt5-default libqt5webkit5-dev qdbus qmlscene qt5-qmake qtbase5-dev-tools qtchooser qtdeclarative5-dev qttools5-dev qtscript5-dev -y
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - sudo apt-get remove cmake
  - wget http://www.cmake.org/files/v3.3/cmake-3.3.1.tar.gz
  - tar xzf cmake-3.3.1.tar.gz
  - cd cmake-3.3.1 && ./configure && make -j3 && sudo make install
  - cd ~/build/qiubix/PirexPickleBlowfish
  - mkdir build && cd build
script: cmake .. && make && GTEST_COLOR=yes make test ARGS="-V"
